name: generate pluginmaster

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 5"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: run
      run: go run generate.go
      
    - name: commit changes
      run: |
        git config user.name "Github Action"
        git config user.email github-actions[bot]@users.noreply.github.com
        git add pluginmaster.json
        git commit -m "[CI] updated pluginmaster.json"
        git push
